# Generated by Django 4.2.4 on 2023-08-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoneAdminTable',
            new_name='AdminTable',
        ),
    ]
